(function initPrismaEstudosCatalog(root, factory) {
  const catalog = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = catalog;
  }
  root.prismaEstudosCatalog = catalog;
})(typeof globalThis !== "undefined" ? globalThis : window, () => {
  const minutes = 45;
  const colors = {
    port: "#38bdf8",
    logic: "#22d3ee",
    pcd: "#8b5cf6",
    ethics: "#a78bfa",
    info: "#0ea5e9",
    const: "#60a5fa",
    admin: "#818cf8",
    publicAdmin: "#22d3ee",
    people: "#fb7185",
    budget: "#7dd3fc",
    labor: "#38bdf8",
    laborProcedure: "#a78bfa"
  };

  const subjectDefinitions = [
    ["cg-port", "Língua Portuguesa", colors.port],
    ["cg-rlm", "Raciocínio Lógico-Matemático", colors.logic],
    ["cg-pcd", "Direitos das Pessoas com Deficiência", colors.pcd],
    ["cg-etica", "Código de Ética dos Servidores do TRT da 2ª Região", colors.ethics],
    ["cg-info", "Noções de Informática", colors.info],
    ["ce-const", "Direito Constitucional", colors.const],
    ["ce-adm", "Direito Administrativo", colors.admin],
    ["ce-adm-pub", "Administração Pública", colors.publicAdmin],
    ["ce-gp", "Gestão de Pessoas", colors.people],
    ["ce-orc", "Orçamento Público", colors.budget],
    ["ce-trab", "Direito do Trabalho", colors.labor],
    ["ce-proc-trab", "Direito Processual do Trabalho", colors.laborProcedure]
  ];

  const generalTopics = {
    "cg-port": [
      "Ortografia e acentuação",
      "Emprego do sinal indicativo de crase",
      "Compreensão e interpretação de textos de gêneros variados",
      "Relação do texto com seu contexto histórico",
      "Denotação e conotação",
      "Discurso direto, indireto e indireto livre",
      "Intertextualidade",
      "Figuras de linguagem",
      "Morfossintaxe",
      "Estrutura e formação de palavras",
      "Sinonímia e antonímia",
      "Pontuação",
      "Pronomes",
      "Concordância nominal e verbal",
      "Flexão nominal e verbal",
      "Vozes do verbo",
      "Correlação de tempos e modos verbais",
      "Regência nominal e verbal",
      "Coordenação e subordinação",
      "Conectivos",
      "Redação: frases corretas e incorretas",
      "Redação: organização e reorganização de orações e períodos",
      "Redação: equivalência e transformação de estruturas"
    ],
    "cg-rlm": [
      "Estrutura lógica de relações arbitrárias",
      "Dedução de novas informações",
      "Raciocínio verbal",
      "Raciocínio matemático",
      "Raciocínio sequencial",
      "Orientação espacial e temporal",
      "Formação de conceitos",
      "Discriminação de elementos",
      "Processo lógico a partir de hipóteses",
      "Regra de três simples",
      "Porcentagem",
      "Acréscimos e descontos",
      "Estatística: média, mediana e moda",
      "Estatística: média ponderada",
      "Medidas de dispersão",
      "Desvio médio, amplitude, variância e desvio padrão",
      "Leitura e interpretação de gráficos e tabelas"
    ],
    "cg-pcd": [
      "Lei nº 13.146/2015",
      "Lei nº 11.126/2005",
      "Constituição Federal",
      "Lei nº 10.098/2000",
      "Decreto nº 5.296/2004",
      "Lei nº 10.048/2000",
      "Lei nº 8.899/1994",
      "Decreto nº 3.691/2000",
      "Lei nº 8.160/1991",
      "Lei nº 7.853/1989",
      "Decreto nº 3.298/1999"
    ],
    "cg-etica": [
      "Código de Ética dos Servidores do Tribunal Regional do Trabalho da 2ª Região"
    ],
    "cg-info": [
      "Windows 10 ou superior",
      "Email",
      "Google Workspace: textos, planilhas e agenda",
      "Google Workspace: apresentações e compartilhamento de arquivos",
      "Internet e Intranet",
      "Navegadores: Internet Explorer, Firefox e Google Chrome",
      "Sites de busca",
      "Grupos de discussão",
      "Redes sociais",
      "Gerenciamento de arquivos, pastas e programas",
      "Segurança da informação",
      "Vírus, worms e outras pragas virtuais",
      "Antivírus, firewall e antispyware"
    ]
  };

  const analystSpecificTopics = {
    "ce-const": [
      "Aplicabilidade e interpretação das normas constitucionais",
      "Vigência e eficácia das normas constitucionais",
      "Controle de constitucionalidade",
      "Sistemas difuso e concentrado",
      "ADI, ADC e ADPF",
      "Princípios fundamentais",
      "Ações constitucionais",
      "Direitos e garantias fundamentais",
      "Direitos sociais",
      "Nacionalidade",
      "Direitos políticos",
      "Partidos políticos",
      "Organização do Estado",
      "Competências da União, Estados, Distrito Federal e Municípios",
      "Administração Pública",
      "Servidores públicos",
      "Organização dos Poderes",
      "Poder Executivo",
      "Poder Legislativo",
      "Poder Judiciário",
      "STF, CNJ, STJ, TST, TRT, Juízes do Trabalho e CSJT",
      "Funções essenciais à Justiça",
      "Ordem econômica e financeira",
      "Finanças públicas",
      "Ordem social"
    ],
    "ce-adm": [
      "Regime jurídico administrativo",
      "Princípios da Administração Pública",
      "LINDB aplicada à Administração Pública",
      "Poderes administrativos",
      "Lei de abuso de autoridade",
      "Atos administrativos",
      "Organização administrativa",
      "Administração direta e indireta",
      "Autarquias, fundações, empresas públicas e sociedades de economia mista",
      "Agentes públicos",
      "Lei nº 8.112/1990",
      "Lei nº 11.416/2006",
      "Regime disciplinar",
      "Processo administrativo disciplinar",
      "Lei nº 9.784/1999",
      "Controle da Administração Pública",
      "Responsabilidade civil do Estado",
      "Improbidade administrativa",
      "Licitações e contratos administrativos",
      "Lei nº 14.133/2021",
      "Pregão eletrônico",
      "Sistema de Registro de Preços",
      "Serviço público",
      "Concessão e permissão",
      "PPP",
      "Entes paraestatais",
      "Bens públicos",
      "Intervenção do Estado na propriedade",
      "Mandado de segurança",
      "Ação popular",
      "Ação civil pública",
      "Habeas data",
      "Lei de Acesso à Informação",
      "LGPD"
    ],
    "ce-adm-pub": [
      "Evolução da Administração Pública",
      "Reforma do Estado",
      "Gestão pública e gestão privada",
      "Gestão da qualidade",
      "Excelência nos serviços públicos",
      "Gestão e avaliação de desempenho",
      "Estruturas organizacionais",
      "Departamentalização",
      "Gestão organizacional",
      "Planejamento estratégico, tático e operacional",
      "Indicadores de desempenho",
      "Gestão por resultados",
      "Balanced Scorecard",
      "Modelagem organizacional",
      "Processos de negócio",
      "Gestão por processos",
      "Gestão de contratos",
      "Gestão por projetos",
      "Escritório de projetos",
      "Gestão de risco",
      "Processo decisório",
      "Mudança e inovação organizacional",
      "Diagnóstico organizacional",
      "Missão, visão e valores",
      "Comunicação na gestão pública"
    ],
    "ce-gp": [
      "Modelos de Gestão de Pessoas",
      "Gestão estratégica de pessoas",
      "Gestão por competências",
      "Gestão do conhecimento",
      "Avaliação de desempenho",
      "Comportamento organizacional",
      "Clima e cultura organizacional",
      "Planejamento de Recursos Humanos",
      "Gestão de conflitos",
      "Indicadores de desempenho",
      "Liderança",
      "Motivação",
      "Satisfação no trabalho",
      "Qualidade de vida no trabalho",
      "Recrutamento e seleção",
      "Análise e descrição de cargos",
      "Treinamento e desenvolvimento",
      "Educação corporativa",
      "Educação à distância"
    ],
    "ce-orc": [
      "Conceitos de orçamento público",
      "Princípios orçamentários",
      "Orçamento-programa",
      "Orçamento na Constituição Federal de 1988",
      "PPA",
      "LDO",
      "LOA",
      "Lei nº 4.320/1964",
      "Receita pública",
      "Despesa pública",
      "Créditos adicionais",
      "Execução orçamentária",
      "Transparência, controle e fiscalização",
      "Lei de Responsabilidade Fiscal",
      "MCASP"
    ],
    "ce-trab": [
      "Princípios e fontes do Direito do Trabalho",
      "Direitos constitucionais dos trabalhadores",
      "Relação de trabalho e relação de emprego",
      "Empregado e empregador",
      "Contrato individual de trabalho",
      "Alteração, suspensão e interrupção do contrato",
      "Rescisão do contrato de trabalho",
      "Aviso prévio",
      "Estabilidade",
      "Jornada de trabalho",
      "Férias",
      "Salário e remuneração",
      "13º salário",
      "FGTS",
      "Segurança e medicina do trabalho",
      "Trabalho do menor",
      "Trabalho da mulher",
      "Direito coletivo do trabalho",
      "Organização sindical",
      "Teletrabalho",
      "Reforma Trabalhista",
      "Súmulas e OJs do TST"
    ],
    "ce-proc-trab": [
      "Fontes do Direito Processual do Trabalho",
      "Justiça do Trabalho",
      "Varas do Trabalho",
      "TRTs",
      "TST",
      "Competência",
      "Serviços auxiliares da Justiça do Trabalho",
      "Ministério Público do Trabalho",
      "Princípios do processo trabalhista",
      "Atos, termos e prazos processuais",
      "Nulidades",
      "Custas e emolumentos",
      "Gratuidade da justiça",
      "Partes e procuradores",
      "Audiências",
      "Provas",
      "Dissídios individuais",
      "Procedimento ordinário e sumaríssimo",
      "Execução trabalhista",
      "Incidente de Desconsideração da Personalidade Jurídica",
      "Penhora",
      "Embargos",
      "Recursos trabalhistas",
      "PJe",
      "Súmulas e OJs do TST"
    ]
  };

  const technicianSpecificTopics = {
    "ce-const": [
      "Princípios fundamentais",
      "Direitos e garantias fundamentais",
      "Direitos sociais",
      "Nacionalidade",
      "Direitos políticos",
      "Organização do Estado",
      "Administração Pública",
      "Servidores públicos",
      "Organização dos Poderes",
      "Poder Executivo",
      "Poder Legislativo",
      "Poder Judiciário",
      "STF, CNJ, STJ, TST, TRT e CSJT",
      "Funções essenciais à Justiça"
    ],
    "ce-adm": [
      "Princípios da Administração Pública",
      "Regime jurídico administrativo",
      "Poderes administrativos",
      "Uso e abuso do poder",
      "Lei de abuso de autoridade",
      "Ato administrativo",
      "Processo administrativo",
      "Lei nº 9.784/1999",
      "Controle da Administração Pública",
      "Improbidade administrativa",
      "Licitações e contratos administrativos",
      "Lei nº 14.133/2021",
      "Pregão eletrônico",
      "Convênios",
      "Parcerias com o terceiro setor",
      "PPP",
      "Serviço público",
      "Concessão e permissão",
      "Agentes públicos",
      "Lei nº 8.112/1990",
      "Lei de Acesso à Informação",
      "LGPD"
    ],
    "ce-adm-pub": [
      "Evolução da Administração Pública",
      "Gestão pública e gestão privada",
      "Gestão da qualidade",
      "Estruturas organizacionais",
      "Planejamento estratégico",
      "Indicadores de desempenho",
      "Gestão por resultados",
      "Gestão por processos",
      "Gestão de contratos",
      "Gestão por projetos",
      "Gestão de risco",
      "Processo decisório",
      "Mudança organizacional",
      "Comunicação na gestão pública"
    ],
    "ce-gp": [
      "Conceitos de Gestão de Pessoas",
      "Modelos de Gestão de Pessoas",
      "Gestão estratégica de pessoas",
      "Gestão por competências",
      "Avaliação de desempenho",
      "Comportamento organizacional",
      "Clima e cultura organizacional",
      "Gestão de conflitos",
      "Indicadores de desempenho",
      "Liderança",
      "Motivação",
      "Qualidade de vida no trabalho",
      "Recrutamento e seleção",
      "Treinamento e desenvolvimento"
    ],
    "ce-orc": [
      "Conceitos de orçamento público",
      "Princípios orçamentários",
      "Orçamento-programa",
      "PPA",
      "LDO",
      "LOA",
      "Lei nº 4.320/1964",
      "Lei de Responsabilidade Fiscal",
      "MCASP"
    ],
    "ce-trab": [
      "Princípios e fontes do Direito do Trabalho",
      "Direitos constitucionais dos trabalhadores",
      "Relação de trabalho e emprego",
      "Contrato individual de trabalho",
      "Jornada de trabalho",
      "Férias",
      "Salário e remuneração",
      "FGTS",
      "Estabilidade",
      "Segurança e medicina do trabalho",
      "Direito coletivo do trabalho",
      "Teletrabalho",
      "Reforma Trabalhista"
    ],
    "ce-proc-trab": [
      "Justiça do Trabalho",
      "Varas do Trabalho",
      "TRTs",
      "TST",
      "Competência",
      "Atos, termos e prazos processuais",
      "Audiências",
      "Provas",
      "Execução trabalhista",
      "Recursos trabalhistas",
      "Processo Judicial Eletrônico"
    ]
  };

  function buildCargo(prefix, cargo, nivel, accent, specificTopics) {
    const subjectIds = subjectDefinitions.map(([key]) => `s-${prefix}-${key}`);
    const subjects = subjectDefinitions.map(([key, name, color]) => ({
      id: `s-${prefix}-${key}`,
      name,
      color,
      isBase: true,
      ownerId: null,
      category: key.startsWith("cg-") ? "Conhecimentos Gerais" : "Conhecimentos Específicos",
      contestId: `${prefix === "a" ? "analista" : "tecnico"}-judiciario-area-administrativa`
    }));
    const topicGroups = { ...generalTopics, ...specificTopics };
    const topics = subjectDefinitions.flatMap(([key]) => (topicGroups[key] || []).map((title, index) => ({
      id: `t-${prefix}-${key}-${String(index + 1).padStart(3, "0")}`,
      subjectId: `s-${prefix}-${key}`,
      title,
      order: index + 1,
      suggestedMinutes: minutes,
      isBase: true,
      ownerId: null
    })));

    return {
      contest: {
        id: `${prefix === "a" ? "analista" : "tecnico"}-judiciario-area-administrativa`,
        name: "TRT 2ª Região",
        cargo,
        role: `${cargo} - Área Administrativa`,
        area: "Administrativa",
        nivel,
        organ: "Tribunal Regional do Trabalho da 2ª Região",
        image: `assets/fotos editais/${prefix === "a" ? "edital-analista-judiciario-area-administrativa.png" : "edital-tecnico-judiciario-area-administrativa.png"}`,
        accent,
        conhecimentosGerais: subjects.filter((subject) => subject.category === "Conhecimentos Gerais").map((subject) => subject.id),
        conhecimentosEspecificos: subjects.filter((subject) => subject.category === "Conhecimentos Específicos").map((subject) => subject.id),
        subjects: subjectIds
      },
      subjects,
      topics
    };
  }

  const analyst = buildCargo("a", "Analista Judiciário", "Superior", "#69a7ff", analystSpecificTopics);
  const technician = buildCargo("t", "Técnico Judiciário", "Médio", "#25d4c8", technicianSpecificTopics);

  return {
    contests: [analyst.contest, technician.contest],
    subjects: [...analyst.subjects, ...technician.subjects],
    topics: [...analyst.topics, ...technician.topics]
  };
});
